services:
  komodod:
    build:
      context: https://github.com/webworker01/kmdocker.git
      dockerfile: Dockerfile
      args:
        PUID: 1000
        PGID: 1000
        REPO: https://github.com/KomodoPlatform/komodo.git
        COMMIT: d456be35acd1f8584e1e4f971aea27bd0644d5c5
        BUILD_THREADS: 2
    environment:
      DAEMON: komodod
      PARAMS: -printtoconsole
    ports:
      - 7770:7770
    volumes:
      - ./entrypoint.sh:/home/komodo/entrypoint.sh
      - /home/yourusername/.komodo/:/home/komodo/.komodo/
      - /home/yourusername/.zcash-params:/home/komodo/.zcash-params
